export const articulos = [
    {
        title: "Journey",
        text: "Spider-Man, the iconic superhero with spider-like abilities, has been swinging through the pages of Marvel Comics for over 50 years. Created by writer Stan Lee and artist Steve Ditko, Spider-Man made his debut in Amazing Fantasy #15 in 1962 and has since become one of the most recognizable and beloved characters in pop culture. Peter Parker, a shy and nerdy high school student, was bitten by a radioactive spider during a science experiment gone wrong. The bite gave Peter incredible strength, speed, and agility, as well as the ability to cling to surfaces and shoot webs from his wrists. With his newfound powers, Peter donned a red and blue suit and became Spider-Man, using his abilities to fight crime and protect the citizens of New York City. Over the years, Spider-Man has faced countless foes, including the Green Goblin, Doctor Octopus, and Venom. But he's also made many allies, such as Mary Jane Watson, Gwen Stacy, and Black Cat. His struggles and triumphs have captured the hearts of fans around the world, and his message of power and responsibility continues to resonate with audiences of all ages. Spider-Man has appeared in numerous comics, television shows, movies, and video games, and his popularity shows no signs of slowing down. He's a symbol of hope and inspiration, reminding us that even the most unlikely heroes can make a difference. So whether you're a longtime fan or a newcomer to the world of Spider-Man, his journey is one that's worth experiencing.",
        src: 'https://images.unsplash.com/photo-1681647627150-f5cb38f3a626?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80',
        id: 'mocd'
    },
    {
        title: "o",
        text: "Spider-Man, the iconic superhero with spider-like abilities, has been swinging through the pages of Marvel Comics for over 50 years. Created by writer Stan Lee and artist Steve Ditko, Spider-Man made his debut in Amazing Fantasy #15 in 1962 and has since become one of the most recognizable and beloved characters in pop culture. Peter Parker, a shy and nerdy high school student, was bitten by a radioactive spider during a science experiment gone wrong. The bite gave Peter incredible strength, speed, and agility, as well as the ability to cling to surfaces and shoot webs from his wrists. With his newfound powers, Peter donned a red and blue suit and became Spider-Man, using his abilities to fight crime and protect the citizens of New York City. Over the years, Spider-Man has faced countless foes, including the Green Goblin, Doctor Octopus, and Venom. But he's also made many allies, such as Mary Jane Watson, Gwen Stacy, and Black Cat. His struggles and triumphs have captured the hearts of fans around the world, and his message of power and responsibility continues to resonate with audiences of all ages. Spider-Man has appeared in numerous comics, television shows, movies, and video games, and his popularity shows no signs of slowing down. He's a symbol of hope and inspiration, reminding us that even the most unlikely heroes can make a difference. So whether you're a longtime fan or a newcomer to the world of Spider-Man, his journey is one that's worth experiencing.",
        src: 'https://images.unsplash.com/photo-1521714161819-15534968fc5f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80',
        id: 'moer'
    },
    {
        title: "The  Spectacular Spider-Man: A Look at the Web-Slinger's Journey",
        text: "Spider-Man, the iconic superhero with spider-like abilities, has been swinging through the pages of Marvel Comics for over 50 years. Created by writer Stan Lee and artist Steve Ditko, Spider-Man made his debut in Amazing Fantasy #15 in 1962 and has since become one of the most recognizable and beloved characters in pop culture. Peter Parker, a shy and nerdy high school student, was bitten by a radioactive spider during a science experiment gone wrong. The bite gave Peter incredible strength, speed, and agility, as well as the ability to cling to surfaces and shoot webs from his wrists. With his newfound powers, Peter donned a red and blue suit and became Spider-Man, using his abilities to fight crime and protect the citizens of New York City. Over the years, Spider-Man has faced countless foes, including the Green Goblin, Doctor Octopus, and Venom. But he's also made many allies, such as Mary Jane Watson, Gwen Stacy, and Black Cat. His struggles and triumphs have captured the hearts of fans around the world, and his message of power and responsibility continues to resonate with audiences of all ages. Spider-Man has appeared in numerous comics, television shows, movies, and video games, and his popularity shows no signs of slowing down. He's a symbol of hope and inspiration, reminding us that even the most unlikely heroes can make a difference. So whether you're a longtime fan or a newcomer to the world of Spider-Man, his journey is one that's worth experiencing.",
        src: 'https://images.unsplash.com/photo-1521714161819-15534968fc5f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80',
        id: 'moyh'
    },
    {
        title: "The Spectacular Spider-Man: A Look at the Web-Slinger's Journey",
        text: "Spider-Man, the iconic superhero with spider-like abilities, has been swinging through the pages of Marvel Comics for over 50 years. Created by writer Stan Lee and artist Steve Ditko, Spider-Man made his debut in Amazing Fantasy #15 in 1962 and has since become one of the most recognizable and beloved characters in pop culture. Peter Parker, a shy and nerdy high school student, was bitten by a radioactive spider during a science experiment gone wrong. The bite gave Peter incredible strength, speed, and agility, as well as the ability to cling to surfaces and shoot webs from his wrists. With his newfound powers, Peter donned a red and blue suit and became Spider-Man, using his abilities to fight crime and protect the citizens of New York City. Over the years, Spider-Man has faced countless foes, including the Green Goblin, Doctor Octopus, and Venom. But he's also made many allies, such as Mary Jane Watson, Gwen Stacy, and Black Cat. His struggles and triumphs have captured the hearts of fans around the world, and his message of power and responsibility continues to resonate with audiences of all ages. Spider-Man has appeared in numerous comics, television shows, movies, and video games, and his popularity shows no signs of slowing down. He's a symbol of hope and inspiration, reminding us that even the most unlikely heroes can make a difference. So whether you're a longtime fan or a newcomer to the world of Spider-Man, his journey is one that's worth experiencing.",
        src: 'https://images.unsplash.com/photo-1521714161819-15534968fc5f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80',
        id: 'moaw'
    },
]